# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI ## work flow name

on:
  push: ## event
    branches: [ "main" ]
  pull_request: #event
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest # containers

    steps:
    - name: Check out the code # check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run test
      run: 
        pytest
